# Generated by Django 4.2.3 on 2023-08-11 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Registered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100, null=True)),
                ("engine_capacity", models.IntegerField()),
                (
                    "assembly",
                    models.CharField(
                        choices=[("Local", "Local"), ("Imported", "Imported")],
                        max_length=10,
                    ),
                ),
                ("make_year", models.IntegerField()),
                ("milage", models.IntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                        max_length=10,
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "body_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carSelling.bodytype",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carSelling.brand",
                    ),
                ),
                (
                    "registered_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carSelling.registered",
                    ),
                ),
            ],
        ),
    ]
