# Generated by Django 4.2.3 on 2023-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carSelling", "0002_rename_registered_registration_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="location",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
